### PR TITLE
string gen instead of lexical cast camintrin uuid

### LINKED ISSUE #295: Bad lexical cast when checking for the camera intrinsic
To my understanding, since PR #280, we require a camera intrinsic to be present in the server to be able to save an image. 
For that, the `uuid_camerainstrinsic` attribute was added in the `ìmage` message:
https://github.com/agri-gaia/seerep/blob/b3cd30a3e8866bf2ee87feddd0ee8e46d0b8a0c8/seerep_msgs/fbs/image.fbs#L18
But if the UUID is not set by a client sending data, the following cast will fail, since invalid memory will be accessed. Interestingly, no segmentation fault occurs. 
https://github.com/agri-gaia/seerep/blob/b3cd30a3e8866bf2ee87feddd0ee8e46d0b8a0c8/seerep_srv/seerep_core_fb/src/core_fb_image.cpp#L47
Therefore, please check if the attribute is set and then access it.

### PR DESCRIPTION
**Pull request by 104H**
Closes #295

### CODE REVIEW

File: seerep_srv/seerep_core_fb/src/core_fb_image.cpp [hunk 1]
```diff
@@ -44,9 +44,11 @@ boost::uuids::uuid CoreFbImage::addData(const seerep::fb::Image& img)
   seerep_core_msgs::DatasetIndexable dataForIndices = CoreFbConversion::fromFb(img);
 
   seerep_core_msgs::camera_intrinsics_query camintrinsics_query;
-  camintrinsics_query.uuidCameraIntrinsics = boost::lexical_cast<boost::uuids::uuid>(img.uuid_cameraintrinsics());
   camintrinsics_query.uuidProject = boost::lexical_cast<boost::uuids::uuid>(img.header()->uuid_project());
```
Comment (Mark-Niemeyer) [inline seerep_srv/seerep_core_fb/src/core_fb_image.cpp:47]: I just saw that this lexical cast has the same problem. Can you address this also in this PR, please?

File: seerep_srv/seerep_core_pb/src/core_pb_image.cpp [hunk 2]
```diff
@@ -44,9 +44,11 @@ boost::uuids::uuid CorePbImage::addData(const seerep::pb::Image& img)
   seerep_core_msgs::DatasetIndexable dataForIndices = CorePbConversion::fromPb(img);
 
   seerep_core_msgs::camera_intrinsics_query camintrinsics_query;
-  camintrinsics_query.uuidCameraIntrinsics = boost::lexical_cast<boost::uuids::uuid>(img.uuid_camera_intrinsics());
   camintrinsics_query.uuidProject = boost::lexical_cast<boost::uuids::uuid>(img.header().uuid_project());
```
Comment (Mark-Niemeyer) [inline seerep_srv/seerep_core_pb/src/core_pb_image.cpp:47]: I just saw that this lexical cast has the same problem. Can you address this also in this PR, please?

**Review by Mark-Niemeyer — CHANGES_REQUESTED** [review]

**Review by Mark-Niemeyer — APPROVED** [review]
